"""Google OAuth2 endpoints — authorize, callback, status, revoke."""
from __future__ import annotations

import secrets
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import RedirectResponse
from google_auth_oauthlib.flow import Flow

from app.adapters.google import GoogleTokenStore
from app.api.deps import get_current_user
from app.config import settings

router = APIRouter(prefix="/oauth/google", tags=["oauth"])

SCOPES = [
    "https://www.googleapis.com/auth/gmail.send",
    "https://www.googleapis.com/auth/gmail.readonly",
    "https://www.googleapis.com/auth/calendar.events",
    "https://www.googleapis.com/auth/drive.readonly",
]

# Store state + code_verifier between authorize and callback
_pending_states: dict[str, dict] = {}


def _build_flow(code_verifier: str | None = None) -> Flow:
    """Build OAuth2 Flow. Pass code_verifier from authorize step in callback."""
    creds_file = Path(settings.google_credentials_file)
    if creds_file.exists():
        flow = Flow.from_client_secrets_file(
            str(creds_file),
            scopes=SCOPES,
            redirect_uri=settings.google_redirect_uri,
            code_verifier=code_verifier,
        )
    else:
        flow = Flow.from_client_config(
            {
                "web": {
                    "client_id": settings.google_client_id,
                    "client_secret": settings.google_client_secret,
                    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
                    "token_uri": "https://oauth2.googleapis.com/token",
                    "redirect_uris": [settings.google_redirect_uri],
                }
            },
            scopes=SCOPES,
            redirect_uri=settings.google_redirect_uri,
            code_verifier=code_verifier,
        )
    return flow


@router.post("/authorize")
async def authorize(user: dict = Depends(get_current_user)) -> dict:
    """Generate Google OAuth2 authorization URL."""
    creds_file = Path(settings.google_credentials_file)
    if not settings.google_client_id and not creds_file.exists():
        raise HTTPException(status_code=501, detail="Google integration not configured")

    flow = _build_flow()
    state = secrets.token_urlsafe(32)

    auth_url, _ = flow.authorization_url(
        access_type="offline",
        include_granted_scopes="true",
        prompt="consent",
        state=state,
    )

    # Save code_verifier (generated by authorization_url) for the callback
    _pending_states[state] = {
        "user_id": user["sub"],
        "code_verifier": flow.code_verifier,
    }
    return {"authorization_url": auth_url}


@router.get("/callback")
async def callback(code: str, state: str) -> RedirectResponse:
    """Handle Google OAuth2 callback — exchange code for tokens."""
    pending = _pending_states.pop(state, None)
    if not pending:
        raise HTTPException(status_code=400, detail="Invalid or expired state")

    user_id = pending["user_id"]
    code_verifier = pending["code_verifier"]

    # Rebuild flow with the SAME code_verifier from the authorize step
    flow = _build_flow(code_verifier=code_verifier)
    flow.fetch_token(code=code)
    credentials = flow.credentials

    if not credentials.refresh_token:
        raise HTTPException(status_code=400, detail="No refresh token. Re-authorize with prompt=consent")

    store = GoogleTokenStore()
    await store.store_token(
        user_id=user_id,
        provider="google",
        refresh_token=credentials.refresh_token,
        scopes=list(credentials.scopes or SCOPES),
    )

    return RedirectResponse(url="http://localhost:5173/settings?google=connected")


@router.get("/status")
async def status(user: dict = Depends(get_current_user)) -> dict:
    """Check if user has valid Google OAuth token."""
    store = GoogleTokenStore()
    connected = await store.has_valid_token(user["sub"], "google")
    return {"connected": connected}


@router.post("/revoke")
async def revoke(user: dict = Depends(get_current_user)) -> dict:
    """Revoke Google OAuth token."""
    store = GoogleTokenStore()
    await store.revoke_token(user["sub"], "google")
    return {"status": "revoked"}
