"""OAuthTokenPort — Protocol for OAuth token storage."""
from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class OAuthTokenPort(Protocol):
    async def store_token(self, user_id: str, provider: str, refresh_token: str, scopes: list[str]) -> None: ...
    async def get_token(self, user_id: str, provider: str) -> str | None: ...
    async def revoke_token(self, user_id: str, provider: str) -> None: ...
    async def has_valid_token(self, user_id: str, provider: str, scope: str | None = None) -> bool: ...
